const maleNames = [
  "James Smith",
  "John Johnson",
  "Robert Williams",
  "Michael Brown",
  "William Jones",
  "David Garcia",
  "Richard Miller",
  "Joseph Davis",
  "Charles Rodriguez",
  "Thomas Martinez",
  "Daniel Hernandez",
  "Matthew Lopez",
  "Christopher Gonzalez",
  "George Wilson",
  "Paul Anderson",
  "Andrew Taylor",
  "Edward Moore",
  "Brian Jackson",
  "Frank Lee",
  "Mark Perez",
  "Liang Chen",
  "Wei Zhao",
  "Yi Liu",
  "Chen Huang",
  "Hao Wu",
  "Guillaume Martin",
  "Jean Bernard",
  "Luc Dubois",
  "Pierre Thomas",
  "Philippe Durand",
  "Mohammed Ali",
  "Omar Ahmed",
  "Abdul Rahman Khan",
  "Musa Sow",
  "Kwame Mensah",
  "Akindele Ade",
  "Chukwuemeka Okoro",
  "Mpho Ndlovu",
  "Lunga Zulu",
  "Zanele Mkhize",
  "Sizwe Nkosi",
  "Eduardo Garcia",
  "Carlos Hernandez",
  "Javier Martinez",
  "Luis Gonzalez",
  "Jose Rodriguez",
  "Miguel Lopez",
  "Rafael Perez",
  "Andres Diaz",
  "Diego Sanchez",
  "Carlos Fernandez",
];

const femaleNames = [
  "Mary Smith",
  "Patricia Johnson",
  "Jennifer Williams",
  "Linda Brown",
  "Elizabeth Jones",
  "Barbara Garcia",
  "Susan Miller",
  "Jessica Davis",
  "Sarah Rodriguez",
  "Karen Martinez",
  "Nancy Hernandez",
  "Lisa Lopez",
  "Betty Gonzalez",
  "Dorothy Wilson",
  "Sandra Anderson",
  "Ashley Taylor",
  "Kimberly Moore",
  "Donna Jackson",
  "Emily Lee",
  "Carol Perez",
  "Xia Li",
  "Yan Wang",
  "Mei Chen",
  "Hui Zhang",
  "Ling Wu",
  "Marie Martin",
  "Sophie Bernard",
  "Isabelle Dubois",
  "Catherine Thomas",
  "Claire Durand",
  "Aisha Ali",
  "Fatima Ahmed",
  "Zahra Khan",
  "Amina Sow",
  "Nana Mensah",
  "Adeola Ade",
  "Chinwe Okoro",
  "Thandeka Ndlovu",
  "Nokuthula Zulu",
  "Nomusa Mkhize",
  "Nandi Nkosi",
  "Maria Garcia",
  "Ana Hernandez",
  "Laura Martinez",
  "Sofia Gonzalez",
  "Carmen Rodriguez",
  "Elena Lopez",
  "Gabriela Perez",
  "Monica Diaz",
  "Silvia Sanchez",
  "Natalia Fernandez",
];

function generateName(sexe) {
  if (sexe === "female" && sexe != undefined) {
    return femaleNames[Math.floor(Math.random() * maleNames.length - 1)];
  } else {
    return maleNames[Math.floor(Math.random() * maleNames.length - 1)];
  }
}
